name: Build
on:
  push:
    branches: main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.8.9"
    - name: Setup poetry 1.1.6
      uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: "1.1.6"
    - name: Install dependencies
      run: poetry install
    - name: Bump Version
      id: bump_version
      run: |
        CURRENT_VERSION="$(poetry version -s)"
        CURRENT_BUILD_NUM="$(echo $CURRENT_VERSION | cut -d '.' -f 2)"
        NEW_VERSION="$(date +%y%m%d).$((CURRENT_BUILD_NUM+1))"
        echo "::set-output name=new_version::${NEW_VERSION}"
        poetry version ${NEW_VERSION}
    - name: Release (Tag in repo)
      run: |
        git config user.name wiris-ci-bot
        git config user.email cicd@wiris.com
        git add pyproject.toml
        git commit -m "cd: Bump version to ${{ steps.bump_version.outputs.new_version }}"
        git tag -a "${{ steps.bump_version.outputs.new_version }}" -m "Release version ${{ steps.bump_version.outputs.new_version }}"
        git push origin master --tags
  publish:
    needs: release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: main
    - name: Set up Python 3.8.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.8.9"
    - name: Setup poetry 1.1.6
      uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: "1.1.6"
    - name: Install dependencies
      run: |
        poetry install
    - name: Build and Publish
      env:
        POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_API_TOKEN }}
      run: echo poetry publish --build
